### ISSUE TITLE
Add an examples folder with the EUROSAT generated STAC Items

### ISSUE THREAD

**Issue by fabricebrito** [ai-extensions/stac-data-loader#1]

**Comment by fmigneault** [comment]
Do we want the data to be directly in the GitHub repository (I'm not sure we even can)?
It is probably better to upload it somewhere else because of the size.
Any preference where that could be?

The data (GeoJSON, GeoTiff, PNG thumbnails) is ~5.1GB.
The STAC Collections and Items are ~322MB.

Otherwise, it only takes a few minutes to generate them from scratch using: https://github.com/ai-extensions/stac-data-loader/blob/main/notebooks/stac_eurosat.ipynb
Just make sure to adjust the first cell to use the full dataset by enabling this part:
```python
DatasetEuroSAT = EuroSAT
```

**Comment by fabricebrito** [comment]
Just a few, 2-3 items is enough, WDYT?

**Comment by fmigneault** [comment]
Sounds good. I'll push this update.

**Comment by fmigneault** [comment]
The samples are now available here: 
https://github.com/ai-extensions/stac-data-loader/tree/main/data/EuroSAT

I used the raw github content endpoints for the URLs, so it should be completely usable as if hosted on a STAC server.

**Comment by fmigneault-crim** [comment]
Already provided in https://github.com/ai-extensions/stac-data-loader/tree/main/data/EuroSAT
Further updates available in https://github.com/ai-extensions/stac-data-loader/pull/2 with better/fixed JSON schema validation.
